### ISSUE TITLE
Manual GUI control from lua

### ISSUE THREAD

**Issue by AndreLouisIssa** [SGG-Modding/Hell2Modding#3]
Add functions to rom.gui to allow mods to open and close the mod GUI manually.

Mainly this is useful for closing the mod gui to open something interactable in-game when a button is pressed on the mod gui.

For opening the mod gui, it could be useful for temporarily hiding the UI to showcase something like an animation/sequence in-game, that was triggered from the mod gui. Or it could be useful for integrating a keyboard input into an otherwise in-game only UI.

**Comment by xiaoxiao921** [comment]
Closed by e9f362d8dcf65aefba78014a9aa6a261c7c99f95
