### ISSUE TITLE
Disable F10 Bug Reporter when mods are enabled

### ISSUE THREAD

**Issue by xiaoxiao921** [SGG-Modding/Hell2Modding#4]
Would just be contaminated reports most of the time

**Comment by PonyWarrior** [comment]
If you do this you need a big fat message telling users they crashed to replace it

**Comment by AndreLouisIssa** [comment]
> If you do this you need a big fat message telling users they crashed to replace it

at least it would show a real error from the log instead of just an empty prompt

**Comment by xiaoxiao921** [comment]
Closed by https://github.com/SGG-Modding/Hell2Modding/commit/518e59aa5f8040ae810695e25169a30d590d4250
