### ISSUE TITLE
Pkg file in memory editing

### ISSUE THREAD

**Issue by xiaoxiao921** [SGG-Modding/Hell2Modding#5]

**Comment by AndreLouisIssa** [comment]
LoadPackages takes a path relative to either the packages folder or the packages/720p folder
if we end up still using LoadPackages, we need a way to know whether it wants the 720p graphics or not.

**Comment by AndreLouisIssa** [comment]
@zanncdwbl has confirmed that absolute paths do not work in LoadPackages, but relative paths do

**Comment by AndreLouisIssa** [comment]
When we are loading additional packages via LoadPackages for 2D graphics, we do not need to care about the checksums or generic data read, only sjson read. Still do not know what is needed for 3D graphics (including their UV textures in packages).

**Comment by xiaoxiao921** [comment]
Closed by 5730b8198f513109e371f37c667d64d0dbfea52f
